ALTER TABLE users
  ADD COLUMN IF NOT EXISTS website TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS instagram TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS youtube TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS tiktok TEXT NOT NULL DEFAULT '';
